algoritmo "retangulo"

var

base,altura,perimetro,diagonal,area:real

inicio

escreva("Base do retagulo= ")
leia(base)
escreval
escreva("Altura do retangulo= ")
leia(altura)
escreval

area<-base * altura
escreval
perimetro<- 2* (base + altura)
escreval
diagonal<- RaizQ (exp(base,2) +exp(altura,2))
escreval

escreval("Area=", area:8:4)
escreval
escreval("Perimetro= ", perimetro:8:4)
escreval
escreval("Diagonal= ", diagonal:8:4)

fimalgoritmo
